### Student Score Analyzer   

📌 Project Overview

This project analyzes student academic performance using Python.
The dataset contains intentional inconsistencies such as missing values, extra spaces, inconsistent text formatting, and outliers to simulate real-world data challenges.

The goal is to clean, process, and analyze the data to extract meaningful insights about student performance.

In [1]:
### importing pandas and loading file
import pandas as pd
student_score = pd.read_excel('student_scores.xlsx')

In [2]:
## viewing data to see how it looks like
student_score.head()

   Student_ID          Name Gender  Math  English  Science   ICT
0           1   EFUA ASANTE      F  85.0     72.0     82.0  92.0
1           2  efua boateng      M  87.0     90.0     76.0  61.0
2           3    efua owusu      F  86.0     47.0     67.0  78.0
3           4   nana mensah      F  82.0     52.0     77.0  95.0
4           5   AKUA APPIAH      M  53.0     43.0     65.0  54.0

In [3]:
## Making a cop of this file before I start editing
data_backup = student_score.copy()

In [4]:
student_score.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  200 non-null    int64
 1   Name        200 non-null    object
 2   Gender      200 non-null    object
 3   Math        187 non-null    float64
 4   English     191 non-null    float64
 5   Science     183 non-null    float64
 6   ICT         190 non-null    float64
dtypes: float64(4), int64(1), object(2)
memory usage: 11.1+ KB

In [5]:
## statistical view of the data
student_score.describe()

       Student_ID        Math     English     Science         ICT
count  200.000000  187.000000  191.000000  183.000000  190.000000
mean   100.500000   67.090909   68.397906   69.180328   66.736842
std     57.879185   17.409899   16.093111   15.421380   15.827583
min      1.000000   40.000000   40.000000   40.000000   40.000000
25%     50.750000   52.000000   55.000000   57.000000   53.000000
50%    100.500000   66.000000   69.000000   71.000000   66.000000
75%    150.250000   81.500000   82.500000   81.000000   79.750000
max    200.000000  150.000000   95.000000   95.000000   95.000000

In [6]:
## Removing all empty spaces before colunm names
student_score.columns = student_score.columns.str.strip()
student_score.columns

Index(['Student_ID', 'Name', 'Gender', 'Math', 'English', 'Science', 'ICT'], dtype='object')

In [7]:
# Removing all empty spaces before name strings of colunm 'Name'
student_score['Name'] = student_score['Name'].str.strip()
student_score['Name'].head()

0     EFUA ASANTE
1    efua boateng
2      efua owusu
3     nana mensah
4     AKUA APPIAH
Name: Name, dtype: object

In [9]:
## Correction name letter organization: Capiatal letter before every name.

student_score['Name'] = student_score['Name'].str.strip().str.title()
student_score['Name']

0       Efua Asante
1      Efua Boateng
2        Efua Owusu
3       Nana Mensah
4       Akua Appiah
           ...
195      Yaw Asante
196     Kwame Darko
197        Kojo Adu
198         Yaw Adu
199       Yaw Gyasi
Name: Name, Length: 200, dtype: object

In [8]:
## changeing all number figures to numbers in case some were entered a strings

subjects = ['Math', 'English', 'Science', 'ICT']

for subject in subjects:
    student_score[subject] = pd.to_numeric(student_score[subject], errors='coerce')
    student_score[subject]
print(student_score[subject])

0      92.0
1      61.0
2      78.0
3      95.0
4      54.0
       ...
195    58.0
196    47.0
197    73.0
198    60.0
199    49.0
Name: ICT, Length: 200, dtype: float64

In [10]:
## Checking number od null values in the data
student_score.isnull().sum()

Student_ID     0
Name           0
Gender         0
Math          13
English        9
Science       17
ICT           10
dtype: int64

In [12]:
### Filling the null values with average of scores of individual
subjects = ['Math', 'English', 'Science', 'ICT']
student_score[subjects] = student_score[subjects].apply(
lambda row: row.fillna(row.mean()),axis = 1
)
student_score.isnull().sum()

Student_ID    0
Name          0
Gender        0
Math          0
English       0
Science       0
ICT           0
dtype: int64

In [13]:
student_score['Total'] = student_score[subjects].sum(axis =1)
student_score.head(20)

,Student_ID,Name,Gender,Math,English,Science,ICT,Total
0,1,Efua Asante,F,85.000000,72.0,82.000000,92.0,331.000000
1,2,Efua Boateng,M,87.000000,90.0,76.000000,61.0,314.000000
2,3,Efua Owusu,F,86.000000,47.0,67.000000,78.0,278.000000
3,4,Nana Mensah,F,82.000000,52.0,77.000000,95.0,306.000000
4,5,Akua Appiah,M,53.000000,43.0,65.000000,54.0,215.000000
5,6,Abena Gyasi,F,55.000000,94.0,76.000000,62.0,287.000000
6,7,Yaw Gyasi,M,92.000000,84.0,92.000000,71.0,339.000000
7,8,Yaw Gyasi,M,49.000000,83.0,64.666667,62.0,258.666667
8,9,Abena Asante,M,150.000000,63.0,83.000000,48.0,344.000000
9,10,Efua Darko,M,62.000000,42.0,48.000000,52.0,204.000000
10,11,Kwame Asante,F,82.000000,41.0,62.000000,63.0,248.000000
11,12,Kofi Gyasi,F,57.000000,47.0,80.000000,69.0,253.000000
12,13,Kojo Asante,M,75.000000,69.0,83.000000,62.0,289.000000
13,14,Kojo Appiah,F,63.333333,74.0,51.000000,65.0,253.333333
14,15,Kofi Adu,M,88.000000,48.0,80.000000,72.0,288.000000
15,16,Kojo Appiah,F,64.000000,82.0,91.000000,61.0,298.000000
16,17,Akua Darko,F,73.000000,48.0,61.000000,55.0,237.000000
17,18,Yaw Boateng,M,79.000000,59.0,95.000000,85.0,318.000000
18,19,Efua Owusu,F,73.000000,65.0,59.000000,92.0,289.000000
19,20,Abena Owusu,F,76.333333,89.0,68.000000,72.0,305.333333

In [14]:
## Creating average of each student score
student_score['Average'] = student_score[subjects].mean(axis=1)
student_score

,Student_ID,Name,Gender,Math,English,Science,ICT,Total,Average
0,1,Efua Asante,F,85.0,72.0,82.0,92.0,331.0,82.75
1,2,Efua Boateng,M,87.0,90.0,76.0,61.0,314.0,78.50
2,3,Efua Owusu,F,86.0,47.0,67.0,78.0,278.0,69.50
3,4,Nana Mensah,F,82.0,52.0,77.0,95.0,306.0,76.50
4,5,Akua Appiah,M,53.0,43.0,65.0,54.0,215.0,53.75
...,...,...,...,...,...,...,...,...,...
195,196,Yaw Asante,M,55.0,76.0,67.0,58.0,256.0,64.00
196,197,Kwame Darko,M,42.0,76.0,61.0,47.0,226.0,56.50
197,198,Kojo Adu,F,87.0,92.0,63.0,73.0,315.0,78.75
198,199,Yaw Adu,M,54.0,89.0,54.0,60.0,257.0,64.25
199,200,Yaw Gyasi,M,47.0,57.0,55.0,49.0,208.0,52.00

In [16]:
student_score['Rank'] = student_score['Total'].rank(ascending=False, method='min')
student_score

,Student_ID,Name,Gender,Math,English,Science,ICT,Total,Average,Rank
0,1,Efua Asante,F,85.0,72.0,82.0,92.0,331.0,82.75,11.0
1,2,Efua Boateng,M,87.0,90.0,76.0,61.0,314.0,78.50,28.0
2,3,Efua Owusu,F,86.0,47.0,67.0,78.0,278.0,69.50,78.0
3,4,Nana Mensah,F,82.0,52.0,77.0,95.0,306.0,76.50,35.0
4,5,Akua Appiah,M,53.0,43.0,65.0,54.0,215.0,53.75,195.0
...,...,...,...,...,...,...,...,...,...,...
195,196,Yaw Asante,M,55.0,76.0,67.0,58.0,256.0,64.00,125.0
196,197,Kwame Darko,M,42.0,76.0,61.0,47.0,226.0,56.50,182.0
197,198,Kojo Adu,F,87.0,92.0,63.0,73.0,315.0,78.75,25.0
198,199,Yaw Adu,M,54.0,89.0,54.0,60.0,257.0,64.25,123.0
199,200,Yaw Gyasi,M,47.0,57.0,55.0,49.0,208.0,52.00,197.0

In [18]:
student_score.sort_values('Rank', ascending= True)

,Student_ID,Name,Gender,Math,English,Science,ICT,Total,Average,Rank
64,65,Yaw Boateng,M,81.0,89.0,95.000000,95.0,360.000000,90.000000,1.0
144,145,Kwame Owusu,M,86.0,91.0,94.000000,89.0,360.000000,90.000000,1.0
8,9,Abena Asante,M,150.0,63.0,83.000000,48.0,344.000000,86.000000,3.0
181,182,Nana Darko,M,88.0,89.0,85.666667,80.0,342.666667,85.666667,4.0
125,126,Kojo Darko,M,93.0,78.0,78.000000,91.0,340.000000,85.000000,5.0
...,...,...,...,...,...,...,...,...,...,...
81,82,Yaw Adu,F,40.0,69.0,53.000000,50.0,212.000000,53.000000,196.0
199,200,Yaw Gyasi,M,47.0,57.0,55.000000,49.0,208.000000,52.000000,197.0
9,10,Efua Darko,M,62.0,42.0,48.000000,52.0,204.000000,51.000000,198.0
111,112,Yaw Mensah,F,61.0,42.0,50.000000,51.0,204.000000,51.000000,198.0
32,33,Efua Owusu,M,48.0,49.0,55.000000,40.0,192.000000,48.000000,200.0